#!/bin/bash

<<-DESCRIPTION
3. Sudarykite shell’o procedurą, kuri priimtų eilę argumentų - katalogų vardų ir:
	• grąžintų vardus pakatalogių, esančių norodytuose kataloguose;
	• jei kreipiantis į šią procedūrą argumentai nenurodyti, tai procedūra turi grąžinti
		vardus pakatalogių, esanč ių einamajame kataloge.
DESCRIPTION

tlk="\t|-"; ## Tree-Like  --  įjungia atvaizdavimą panašų į katalogų medį
#tlk=""; ## - išjungtas tlk. Atkomentuok eilutę, jei nori gauti paprastą išvestį.

if [ "$1" = "" ]; then
	echo -ne "\nKatalogai, esantys darbiniame kataloge:\n\n$(pwd)\n";
	for i in $(ls "$(pwd)/"); do
		printf "$tree $i\n";
	done;
exit 0;
fi;

for i in $*; do
	if [ "$1" == "-s" ] ; then continue; fi;
	if [ "$(ls -lhad "$i"|egrep -c ^d)" == "1" ]; then
		echo -ne "\n\t$i\n";
### Šis variantas tiktų tik jei būtų naudojami aplankų pavadinimai, sudaryti iš vieno žodžio. ###
#		for f in $(ls "$i"); do
#			if [ "$(ls -lhd "$i/$f" 2>/dev/null|egrep -c ^d)" == "1" ]; then echo -ne "$tree $f\n";fi;
#		done;

		ls -la "$i" | egrep  ^d|awk "{\$1=\$2=\$3=\$4=\$5=\$6=\$7=\$8=\"\"; print \"$tlk\"\$0}"|sed s'/    *//g';

	

	fi;
done;
